apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc   #gke cluster api ip, context needs to be added https://argo-cd.readthedocs.io/en/stable/getting_started/
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/mrdylans/argocd.git 
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
