apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-stg
  namespace: demo-app-stg
spec:
  destination:
    namespace: demo-app-stg
    server: ''
  source:
    path: charts/demo-app/hello/stg
    repoURL: git@github.com:mrdylans/argocd.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-helm3
      env:
        - name: HELM_ARGS
          value: '-f values-stg.yaml'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      selfHeal: true
