apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app-hello
    app.kubernetes.io/managed-by: Helm
  name: demo-app-hello
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  selector:
    service: demo-app-hello
